// packages/react/markput/src/components/Popup/ListItem.tsx
import {cx} from '@markput/core'
import type {MouseEvent, ReactNode} from 'react'
import {useEffect, useRef} from 'react'

import styles from '@markput/core/styles.module.css'

export const ListItem = ({
	onClick,
	active,
	children,
}: {
	onClick?: (e: MouseEvent<HTMLLIElement>) => void
	active?: boolean
	children: ReactNode
}) => {
	const ref = useRef<HTMLLIElement>(null)

	useEffect(() => {
		if (active) ref.current?.scrollIntoView(false)
	}, [active])

	return (
		<li ref={ref} className={cx(styles.PopupItem, active && styles.PopupItemActive)} onClick={onClick}>
			{children}
		</li>
	)
}

// packages/vue/markput/src/components/Popup/ListItem.vue
<script setup lang="ts">
import {ref, watch} from 'vue'

import styles from '@markput/core/styles.module.css'

const props = defineProps<{active?: boolean}>()

const itemEl = ref<HTMLLIElement | null>(null)

watch(
	() => props.active,
	val => {
		if (val) itemEl.value?.scrollIntoView(false)
	}
)
</script>

<template>
	<li ref="itemEl" :class="[styles.PopupItem, active && styles.PopupItemActive]">
		<slot />
	</li>
</template>
