// packages/vue/markput/src/components/TextSpan.vue
<script setup lang="ts">
import {inject, ref, computed, watch, onMounted} from 'vue'
import {resolveSlot, resolveSlotProps} from '../lib/utils/resolveSlot'
import {useStore} from '../lib/hooks/useStore'
import {TOKEN_KEY} from '../lib/providers/tokenKey'

const store = useStore()
const tokenRef = inject(TOKEN_KEY)!
const token = tokenRef.value
const elRef = ref<HTMLSpanElement | null>(null)

const readOnly = store.state.readOnly.use()
const slots = store.state.slots.use()
const slotProps = store.state.slotProps.use()
const spanTag = computed(() => resolveSlot('span', slots.value))
const spanProps = computed(() => resolveSlotProps('span', slotProps.value))

if (token.type !== 'text') {
	throw new Error('TextSpan component expects a TextToken')
}

onMounted(() => {
	if (elRef.value && elRef.value.textContent !== token.content) {
		elRef.value.textContent = token.content
	}
})

watch(
	() => token.content,
	content => {
		if (elRef.value && elRef.value.textContent !== content) {
			elRef.value.textContent = content
		}
	}
)

function handlePaste(e: ClipboardEvent) {
	e.preventDefault()
	const text = e.clipboardData?.getData('text')
	if (text) document.execCommand('insertText', false, text)
}
</script>

<template>
	<component
		:is="spanTag"
		:ref="(el: any) => (elRef = el)"
		v-bind="spanProps"
		:contenteditable="!readOnly"
		@paste="handlePaste"
	/>
</template>

// packages/markput/src/components/TextSpan.tsx
import {ClipboardEvent, useRef} from 'react'
import {getChildProps} from '../utils/functions/getChildProps'
import {useStore} from '../utils/hooks/useStore'
import {useToken} from '../utils/providers/TokenProvider'

// TextSpan - renders text tokens (non-annotated text)
export const TextSpan = () => {
	const token = useToken()
	const ref = useRef<HTMLSpanElement>(null)
	const readOnly = useStore(state => state.props.readOnly)
	const spanOverride = useStore(getChildProps('span'), true)

	// Ensure it's a TextToken
	if (token.type !== 'text') {
		throw new Error('TextSpan component expects a TextToken')
	}

	return (
		<span
			{...spanOverride}
			ref={ref}
			contentEditable={!readOnly}
			onPaste={handlePaste}
			suppressContentEditableWarning
		>
			{token.content}
		</span>
	)
}

function handlePaste(e: ClipboardEvent<HTMLSpanElement>) {
	e.preventDefault()
	const text = e.clipboardData.getData('text')
	document.execCommand('insertText', false, text)
}
