// packages/react/markput/src/components/BlockMenu.tsx
import {cx} from '@markput/core'
import type {Token} from '@markput/core'
import {memo, useMemo} from 'react'

import {useMarkput} from '../lib/hooks/useMarkput'
import {List} from './Popup/List'
import {ListItem} from './Popup/ListItem'
import {Popup} from './Popup/Popup'

import styles from '@markput/core/styles.module.css'

export const BlockMenu = memo(({token}: {token: Token}) => {
	const {blockStore, menuOpen, menuPosition, tokens, index} = useMarkput(s => {
		const blockStore = s.block.get(token)

		return {
			blockStore,
			menuOpen: blockStore.state.menuOpen,
			menuPosition: blockStore.state.menuPosition,
			tokens: s.tokens,
			index: s.tokens.index,
		}
	})
	const path = index.pathFor(token)
	const controlRef = useMemo(() => (path ? tokens.control(path) : undefined), [tokens, path])

	if (!menuOpen) return null

	return (
		<Popup
			ref={(el: HTMLDivElement | null) => {
				blockStore.attachMenu(el)
				controlRef?.(el)
			}}
			style={{top: menuPosition.top, left: menuPosition.left}}
		>
			<List>
				<ListItem onClick={() => blockStore.addBlock()}>
					<span className={cx(styles.Icon, styles.IconAdd)} />
					<span>Add below</span>
				</ListItem>
				<ListItem onClick={() => blockStore.duplicateBlock()}>
					<span className={cx(styles.Icon, styles.IconDuplicate)} />
					<span>Duplicate</span>
				</ListItem>
				<ListItem onClick={() => blockStore.deleteBlock()}>
					<span className={cx(styles.Icon, styles.IconTrash)} />
					<span>Delete</span>
				</ListItem>
			</List>
		</Popup>
	)
})

BlockMenu.displayName = 'BlockMenu'

// packages/vue/markput/src/components/BlockMenu.vue
<script setup lang="ts">
import type {Token as TokenType} from '@markput/core'

import {useMarkput} from '../lib/hooks/useMarkput'
import {useStore} from '../lib/hooks/useStore'
import List from './Popup/List.vue'
import ListItem from './Popup/ListItem.vue'
import Popup from './Popup/Popup.vue'

import styles from '@markput/core/styles.module.css'

const props = defineProps<{token: TokenType}>()

const store = useStore()
const blockStore = store.block.get(props.token)
const index = useMarkput(s => s.tokens.index)
const menuOpen = useMarkput(() => blockStore.state.menuOpen)
const menuPosition = useMarkput(() => blockStore.state.menuPosition)

let menuControlRef: ((element: HTMLElement | null) => void) | undefined

const getMenuControlRef = () => {
	if (menuControlRef) return menuControlRef
	const path = index.value.pathFor(props.token)
	if (!path) return undefined
	menuControlRef = store.tokens.control(path)
	return menuControlRef
}

const setMenuRef = (el: HTMLElement | null) => {
	blockStore.attachMenu(el)
	getMenuControlRef()?.(el)
}
</script>

<template>
	<Popup
		v-if="menuOpen"
		:attach-ref="setMenuRef"
		:style="{top: menuPosition.top + 'px', left: menuPosition.left + 'px'}"
	>
		<List>
			<ListItem @mousedown.prevent="blockStore.addBlock()">
				<span :class="[styles.Icon, styles.IconAdd]" />
				<span>Add below</span>
			</ListItem>
			<ListItem @mousedown.prevent="blockStore.duplicateBlock()">
				<span :class="[styles.Icon, styles.IconDuplicate]" />
				<span>Duplicate</span>
			</ListItem>
			<ListItem @mousedown.prevent="blockStore.deleteBlock()">
				<span :class="[styles.Icon, styles.IconTrash]" />
				<span>Delete</span>
			</ListItem>
		</List>
	</Popup>
</template>
