// packages/react/markput/src/components/ChromeLayer.tsx
import {BLOCK_MENU_ITEMS, cx, getAlwaysShowHandle} from '@markput/core'
import type {RowBox} from '@markput/core'
import {memo, useEffect, useLayoutEffect, useMemo, useState} from 'react'

import {useMarkput} from '../lib/hooks/useMarkput'
import {List} from './Popup/List'
import {ListItem} from './Popup/ListItem'
import {Popup} from './Popup/Popup'

import styles from '@markput/core/styles.module.css'

/**
 * ONE absolutely positioned chrome layer per editor: it paints the grip, the drop indicator and
 * the row menu at row boxes it MEASURES, where `.Block { position: relative }` used to make them
 * free inside every row.
 *
 * It lives INSIDE the container — the alternative, a new wrapper element in `MarkedInput`, would
 * impose a published DOM change on every consumer for internal convenience. That puts it inside
 * the editing host, so it registers as a `control()` root: one registration for the whole editor,
 * where the per-row chrome filed up to four PER ROW, and everything painted inside it inherits
 * `isContentEditable === false` from it.
 */
const iconGrip = `${styles.Icon} ${styles.IconGrip}`

export const ChromeLayer = memo(() => {
	const {chrome, tokens, readOnly, draggable, rows, hovered, dragging, drop, menu, geometry} = useMarkput(s => ({
		chrome: s.chrome,
		tokens: s.tokens,
		readOnly: s.props.readOnly,
		draggable: s.props.draggable,
		rows: s.tokens.nodes,
		hovered: s.chrome.state.hovered,
		dragging: s.chrome.state.dragging,
		drop: s.chrome.state.drop,
		menu: s.chrome.state.menu,
		geometry: s.chrome.state.geometry,
	}))
	const controlRef = useMemo(() => tokens.control(), [tokens])
	const alwaysShowHandle = useMemo(() => getAlwaysShowHandle(draggable), [draggable])

	// The row the grip decorates: the dragged row while a drag is live, else the hovered one.
	// The fallback is what `alwaysShowHandle` now means — one layer cannot paint a grip on every
	// row, so the option is "one grip, on the row nearest the pointer", resting on the first row
	// while the pointer is away. DECLARED BEHAVIOUR CHANGE on a published option.
	const gripRow = dragging ?? hovered ?? (alwaysShowHandle ? (rows[0]?.id ?? null) : null)
	const dropRow = drop?.id ?? null

	// Geometry is MEASURED, not inherited from a `position: relative` ancestor. In a layout
	// effect, so it sees the painted DOM of this very commit, and re-run on `geometry` — the
	// container's own resize/scroll clock.
	const [gripBox, setGripBox] = useState<RowBox | null>(null)
	const [dropBox, setDropBox] = useState<RowBox | null>(null)
	useLayoutEffect(() => {
		setGripBox(gripRow === null ? null : (chrome.boxOf(gripRow) ?? null))
		setDropBox(dropRow === null ? null : (chrome.boxOf(dropRow) ?? null))
	}, [chrome, gripRow, dropRow, geometry])

	// A row that GROWS as the user types moves the grip with it, and the container's own observer
	// says nothing when the container's size is fixed. Observing the ONE decorated row is the
	// cheapest correct trigger.
	useEffect(() => {
		if (gripRow === null) return
		const element = tokens.handle(gripRow)?.element()
		if (!element) return
		const observer = new ResizeObserver(() => setGripBox(chrome.boxOf(gripRow) ?? null))
		observer.observe(element)
		return () => observer.disconnect()
	}, [chrome, tokens, gripRow])

	return (
		<div ref={controlRef} className={styles.ChromeLayer}>
			{!readOnly && gripRow !== null && gripBox !== null && (
				<div
					className={cx(
						styles.SidePanel,
						// Painted but INVISIBLE while its row is being dragged, as the per-row
						// panel was: the grip stays mounted so its own `dragend` still fires
						// (Chromium sends no mouseup for a drag), and the pointer is away with
						// the drag image anyway.
						alwaysShowHandle ? styles.SidePanelAlways : dragging === null && styles.SidePanelVisible
					)}
					// `left` is the ROW's left edge; `.SidePanel`'s negative margin hangs the
					// band off it. The layer's own origin would put it on top of the text
					// wherever core reserves no gutter — `draggable: false`.
					style={{top: gripBox.top, left: gripBox.left, height: gripBox.height}}
				>
					<button
						type="button"
						// The grip is also the menu trigger, so it renders in block mode regardless;
						// `draggable` gates only the drag affordance it carries.
						draggable={!!draggable}
						className={cx(styles.GripButton, dragging !== null && styles.GripButtonDragging)}
						aria-label={draggable ? 'Drag to reorder or click for options' : 'Block options'}
						onMouseDown={chrome.pinHover}
						onDragStart={e => chrome.beginDrag(gripRow, e.nativeEvent)}
						onDragEnd={() => chrome.endDrag()}
						onClick={e => {
							e.preventDefault()
							chrome.openMenu(gripRow, e.currentTarget.getBoundingClientRect())
						}}
					>
						<span className={iconGrip} />
					</button>
				</div>
			)}

			{drop && dropBox && (
				<div
					className={styles.DropIndicator}
					style={{
						top: drop.edge === 'before' ? dropBox.top - 1 : dropBox.top + dropBox.height - 1,
						left: dropBox.left,
						width: dropBox.width,
					}}
				/>
			)}

			{menu && (
				<Popup
					ref={(el: HTMLElement | null) => {
						chrome.menuElement(el)
					}}
					style={{top: menu.top, left: menu.left, pointerEvents: 'auto'}}
				>
					<List>
						{BLOCK_MENU_ITEMS.map(item => (
							<ListItem key={item.label} onClick={() => item.run(chrome)}>
								<span className={item.iconClass} />
								<span>{item.label}</span>
							</ListItem>
						))}
					</List>
				</Popup>
			)}
		</div>
	)
})

ChromeLayer.displayName = 'ChromeLayer'

// packages/vue/markput/src/components/ChromeLayer.vue
<script setup lang="ts">
import {BLOCK_MENU_ITEMS, getAlwaysShowHandle} from '@markput/core'
import type {RowBox} from '@markput/core'
import {computed, onScopeDispose, ref, watchEffect} from 'vue'

import {useMarkput} from '../lib/hooks/useMarkput'
import {useStore} from '../lib/hooks/useStore'
import {unwrapEl} from '../lib/unwrapEl'
import List from './Popup/List.vue'
import ListItem from './Popup/ListItem.vue'
import Popup from './Popup/Popup.vue'

import styles from '@markput/core/styles.module.css'

/**
 * ONE absolutely positioned chrome layer per editor — the Vue mirror of the React
 * `ChromeLayer`, over the SAME `ChromeModel`. Every decision is core's: the hover pin, the
 * hit-test, the drop edge and the menu's row all live there, so this file is a painter.
 */
const store = useStore()
const chrome = store.chrome

const readOnly = useMarkput(s => s.props.readOnly)
const draggable = useMarkput(s => s.props.draggable)
const rows = useMarkput(s => s.tokens.nodes)
const hovered = useMarkput(() => chrome.state.hovered)
const dragging = useMarkput(() => chrome.state.dragging)
const drop = useMarkput(() => chrome.state.drop)
const menu = useMarkput(() => chrome.state.menu)
const geometry = useMarkput(() => chrome.state.geometry)

const controlRef = store.tokens.control()
const setLayerRef = (el: unknown) => controlRef(unwrapEl(el))
const setMenuRef = (el: HTMLElement | null) => chrome.menuElement(el)

const alwaysShowHandle = computed(() => getAlwaysShowHandle(draggable.value))

// The row the grip decorates: the dragged row while a drag is live, else the hovered one. The
// fallback is what `alwaysShowHandle` now means — one layer cannot paint a grip on every row,
// so the option is "one grip, on the row nearest the pointer", resting on the first row while
// the pointer is away. DECLARED BEHAVIOUR CHANGE on a published option.
const gripRow = computed<number | null>(
	() => dragging.value ?? hovered.value ?? (alwaysShowHandle.value ? (rows.value[0]?.id ?? null) : null)
)
const dropRow = computed<number | null>(() => drop.value?.id ?? null)

// Geometry is MEASURED, not inherited from a `position: relative` ancestor: `geometry` is the
// container's resize/scroll clock and `flush: 'post'` puts the read after this patch painted.
const gripBox = ref<RowBox | null>(null)
const dropBox = ref<RowBox | null>(null)
const measure = () => {
	gripBox.value = gripRow.value === null ? null : (chrome.boxOf(gripRow.value) ?? null)
	dropBox.value = dropRow.value === null ? null : (chrome.boxOf(dropRow.value) ?? null)
}
watchEffect(
	() => {
		void geometry.value
		void gripRow.value
		void dropRow.value
		measure()
	},
	{flush: 'post'}
)

// A row that GROWS as the user types moves the grip with it, and the container's own observer
// says nothing when the container's size is fixed. Observing the ONE decorated row is the
// cheapest correct trigger.
let observer: ResizeObserver | undefined
watchEffect(
	() => {
		observer?.disconnect()
		observer = undefined
		const id = gripRow.value
		if (id === null) return
		const element = store.tokens.handle(id)?.element()
		if (!element) return
		observer = new ResizeObserver(() => {
			gripBox.value = chrome.boxOf(id) ?? null
		})
		observer.observe(element)
	},
	{flush: 'post'}
)
onScopeDispose(() => observer?.disconnect())

// `left` is the ROW's left edge; `.SidePanel`'s negative margin hangs the band off it. The
// layer's own origin would put it on top of the text wherever core reserves no gutter
// (`draggable: false`).
const gripStyle = computed(() => ({
	top: `${gripBox.value?.top ?? 0}px`,
	left: `${gripBox.value?.left ?? 0}px`,
	height: `${gripBox.value?.height ?? 0}px`,
}))
const dropStyle = computed(() => {
	const box = dropBox.value
	const edge = drop.value?.edge
	if (!box || !edge) return undefined
	return {
		top: `${edge === 'before' ? box.top - 1 : box.top + box.height - 1}px`,
		left: `${box.left}px`,
		width: `${box.width}px`,
	}
})
</script>

<template>
	<div :ref="setLayerRef" :class="styles.ChromeLayer">
		<!-- Painted but INVISIBLE while its row is being dragged, as the per-row panel was: the
		     grip stays mounted so its own `dragend` still fires (Chromium sends no mouseup for a
		     drag), and the pointer is away with the drag image anyway. -->
		<div
			v-if="!readOnly && gripRow !== null && gripBox"
			:class="[
				styles.SidePanel,
				alwaysShowHandle ? styles.SidePanelAlways : dragging === null && styles.SidePanelVisible,
			]"
			:style="gripStyle"
		>
			<!-- The grip is also the menu trigger, so it renders in block mode regardless;
			     `draggable` gates only the drag affordance it carries. -->
			<button
				type="button"
				:draggable="!!draggable"
				:class="[styles.GripButton, dragging !== null && styles.GripButtonDragging]"
				:aria-label="draggable ? 'Drag to reorder or click for options' : 'Block options'"
				@mousedown="chrome.pinHover()"
				@dragstart="e => chrome.beginDrag(gripRow!, e)"
				@dragend="chrome.endDrag()"
				@click.prevent="
					e => chrome.openMenu(gripRow!, (e.currentTarget as HTMLElement).getBoundingClientRect())
				"
			>
				<span :class="`${styles.Icon} ${styles.IconGrip}`" />
			</button>
		</div>

		<div v-if="dropStyle" :class="styles.DropIndicator" :style="dropStyle" />

		<Popup
			v-if="menu"
			:attach-ref="setMenuRef"
			:style="{top: menu.top + 'px', left: menu.left + 'px', pointerEvents: 'auto'}"
		>
			<List>
				<ListItem v-for="item in BLOCK_MENU_ITEMS" :key="item.label" @mousedown.prevent="item.run(chrome)">
					<span :class="item.iconClass" />
					<span>{{ item.label }}</span>
				</ListItem>
			</List>
		</Popup>
	</div>
</template>
