// packages/react/markput/src/components/MarkedInput.tsx
import type {ComponentType, CSSProperties, Ref} from 'react'
import {useMemo, useState} from 'react'
import type {MarkedInputHandler, MarkProps, Option, OverlayProps, SlotProps, Slots} from '../types'
import {Container} from './Container'
import {Whisper} from './Whisper'
import type {CoreSlotProps, CoreSlots, OverlayTrigger, StyleProperties} from '@markput/core'
import {cx, merge, Store} from '@markput/core'
import styles from '@markput/core/styles.module.css'
import {StoreContext} from '../lib/providers/StoreContext'
import {useCoreFeatures} from '../lib/hooks/useCoreFeatures'
import {createUseSignalHook} from '../lib/hooks/createUseSignalHook'
import {DEFAULT_OPTIONS} from '../constants'

export interface MarkedInputProps<TMarkProps = MarkProps, TOverlayProps = OverlayProps> {
	ref?: Ref<MarkedInputHandler>
	Mark?: ComponentType<TMarkProps>
	Overlay?: ComponentType<TOverlayProps>
	options?: Option<TMarkProps, TOverlayProps>[]
	className?: string
	style?: CSSProperties
	slots?: Slots
	slotProps?: SlotProps
	showOverlayOn?: OverlayTrigger
	value?: string
	defaultValue?: string
	onChange?: (value: string) => void
	readOnly?: boolean
}

export function MarkedInput<TMarkProps = MarkProps, TOverlayProps = OverlayProps>(
	props: MarkedInputProps<TMarkProps, TOverlayProps>
) {
	const {
		ref,
		value,
		defaultValue,
		onChange,
		readOnly,
		Mark,
		Overlay,
		slots,
		slotProps,
		options = DEFAULT_OPTIONS,
		showOverlayOn = 'change',
		className: classNameProp,
		style: styleProp,
	} = props
	const className = cx(styles.Container, classNameProp, slotProps?.container?.className)
	const style = merge(styleProp, slotProps?.container?.style)
	const createUseHook = useMemo(createUseSignalHook, [])
	const [store] = useState(() => {
		const s = new Store({createUseHook})
		s.state.value.set(value)
		s.state.defaultValue.set(defaultValue)
		s.state.onChange.set(onChange)
		s.state.readOnly.set(readOnly ?? false)
		s.state.options.set(options)
		s.state.showOverlayOn.set(showOverlayOn)
		s.state.Mark.set(Mark)
		s.state.Overlay.set(Overlay)
		s.state.className.set(className)
		s.state.style.set(style as StyleProperties)
		s.state.slots.set(slots as CoreSlots)
		s.state.slotProps.set(slotProps as CoreSlotProps)
		return s
	})

	store.state.value.set(value)
	store.state.defaultValue.set(defaultValue)
	store.state.onChange.set(onChange)
	store.state.readOnly.set(readOnly ?? false)
	store.state.options.set(options)
	store.state.showOverlayOn.set(showOverlayOn)
	store.state.Mark.set(Mark)
	store.state.Overlay.set(Overlay)
	store.state.className.set(className)
	store.state.style.set(style as StyleProperties)
	store.state.slots.set(slots as CoreSlots)
	store.state.slotProps.set(slotProps as CoreSlotProps)

	useCoreFeatures(store, ref)

	return (
		<StoreContext.Provider value={store}>
			<Container />
			<Whisper />
		</StoreContext.Provider>
	)
}

// packages/vue/markput/src/components/MarkedInput.vue
<script setup lang="ts">
import type {CoreSlotProps, CoreSlots, MarkputHandler, StyleProperties} from '@markput/core'
import {cx, DEFAULT_OPTIONS, merge, Store} from '@markput/core'
import {computed, provide, shallowRef, watch} from 'vue'

import {createUseHook} from '../lib/hooks/createUseHook'
import {useCoreFeatures} from '../lib/hooks/useCoreFeatures'
import {STORE_KEY} from '../lib/providers/storeKey'
import type {MarkedInputProps} from '../types'
import Container from './Container.vue'
import DragContainer from './DragContainer.vue'
import OverlayRenderer from './OverlayRenderer.vue'

import styles from '@markput/core/styles.module.css'

const props = withDefaults(defineProps<MarkedInputProps>(), {
	options: () => DEFAULT_OPTIONS,
	showOverlayOn: 'change',
	readOnly: false,
	drag: false,
})

const ContainerImpl = computed(() => (props.drag ? DragContainer : Container))

const emit = defineEmits<{
	change: [value: string]
}>()

const store = shallowRef(new Store({createUseHook}))

provide(STORE_KEY, store.value)

function syncProps() {
	const className = cx(styles.Container, props.className, props.slotProps?.container?.className as string | undefined)
	const style = merge(
		props.style as StyleProperties | undefined,
		props.slotProps?.container?.style as StyleProperties | undefined
	)

	store.value.state.set({
		value: props.value,
		defaultValue: props.defaultValue,
		onChange: (v: string) => emit('change', v),
		readOnly: props.readOnly,
		drag: props.drag,
		options: props.options,
		showOverlayOn: props.showOverlayOn,
		Mark: props.Mark,
		Overlay: props.Overlay,
		className,
		style: style as StyleProperties,
		slots: props.slots as CoreSlots,
		slotProps: props.slotProps as CoreSlotProps,
	})
}

syncProps()

watch(
	() => [
		props.value,
		props.defaultValue,
		props.readOnly,
		props.options,
		props.showOverlayOn,
		props.Mark,
		props.Overlay,
		props.className,
		props.style,
		props.slots,
		props.slotProps,
		props.drag,
	],
	syncProps
)

useCoreFeatures(store.value)

const handler: MarkputHandler = store.value.createHandler()
defineExpose(handler)
</script>

<template>
	<component :is="ContainerImpl" />
	<OverlayRenderer />
</template>
