// packages/react/markput/src/components/OverlayRenderer.tsx
import {key} from '@markput/core'
import {memo, useMemo} from 'react'

import {useMarkput} from '../lib/hooks/useMarkput'
import {Suggestions} from './Suggestions'

export const OverlayRenderer = memo(() => {
	const {match, resolveOverlay} = useMarkput(s => ({
		match: s.overlay.match,
		resolveOverlay: s.overlay.slot,
	}))
	const overlayKey = useMemo(() => (match ? key.get(match.option) : undefined), [match])

	const [Overlay, props] = resolveOverlay(match?.option, Suggestions)

	if (!overlayKey) return

	return <Overlay key={overlayKey} {...props} />
})

OverlayRenderer.displayName = 'OverlayRenderer'

// packages/vue/markput/src/components/OverlayRenderer.vue
<script setup lang="ts">
import type {OverlayMatch} from '@markput/core'
import {computed, type Ref} from 'vue'

import {useMarkput} from '../lib/hooks/useMarkput'
import {useStore} from '../lib/hooks/useStore'
import type {Option} from '../types'
import Suggestions from './Suggestions/Suggestions.vue'

const store = useStore()
const overlayMatchRef = useMarkput(s => s.state.overlayMatch) as Ref<OverlayMatch<Option> | undefined>
const overlayKey = computed(() => (overlayMatchRef.value ? store.key.get(overlayMatchRef.value.option) : undefined))
const resolveOverlay = useMarkput(s => s.computed.overlay)

const resolved = computed(() => {
	const match = overlayMatchRef.value
	if (!match) return null
	return resolveOverlay.value(match.option, Suggestions)
})
</script>

<template>
	<component v-if="overlayKey && resolved" :is="resolved[0]" :key="overlayKey" v-bind="resolved[1]" />
</template>
