// packages/markput/src/components/Token.tsx
import {memo} from 'react'
import type {Token as TokenType} from '@markput/core'
import {TokenProvider} from '../lib/providers/TokenProvider'
// eslint-disable-next-line import/no-cycle
import {MarkRenderer} from './MarkRenderer'
import {TextSpan} from './TextSpan'

/** Renders a token - marks via MarkRenderer, text via TextSpan or plain text if nested */
export const Token = memo(({mark, isNested = false}: {mark: TokenType; isNested?: boolean}) => {
	if (mark.type === 'mark') {
		return (
			<TokenProvider value={mark}>
				<MarkRenderer />
			</TokenProvider>
		)
	}

	if (isNested) {
		return <>{mark.content}</>
	}

	return (
		<TokenProvider value={mark}>
			<TextSpan />
		</TokenProvider>
	)
})

Token.displayName = 'Token'

// packages/vue/markput/src/components/Token.vue
<script lang="ts">
import type {Token as TokenType} from '@markput/core'
import {defineComponent, h, provide, toRef, type PropType} from 'vue'

import {TOKEN_KEY} from '../lib/providers/tokenKey'
// eslint-disable-next-line import/no-cycle
import MarkRenderer from './MarkRenderer.vue'
import TextSpan from './TextSpan.vue'

export default defineComponent({
	props: {
		mark: {type: Object as PropType<TokenType>, required: true},
		isNested: {type: Boolean, default: false},
	},
	setup(props) {
		provide(
			TOKEN_KEY,
			toRef(() => props.mark)
		)

		return () => {
			if (props.mark.type === 'mark') return h(MarkRenderer)
			if (props.isNested) return props.mark.content
			return h(TextSpan)
		}
	},
})
</script>
