// packages/vue/markput/src/components/BlockControls.vue
<script setup lang="ts">
import {ROW_MENU_ITEMS, getAlwaysShowHandle} from '@markput/core'
import type {RowBox} from '@markput/core'
import {computed, onScopeDispose, ref, watchEffect} from 'vue'

import {useMarkput} from '../lib/hooks/useMarkput'
import {useStore} from '../lib/hooks/useStore'
import {unwrapEl} from '../lib/unwrapEl'
import List from './Popup/List.vue'
import ListItem from './Popup/ListItem.vue'
import Popup from './Popup/Popup.vue'

import styles from '@markput/core/styles.module.css'

/**
 * ONE absolutely positioned row-controls layer per editor — the Vue mirror of the React
 * `BlockControls`, over the SAME `RowController`. Every decision is core's: the hover pin, the
 * hit-test, the drop edge and the menu's row all live there, so this file is a painter.
 *
 * `BlockControls`, not `BlockLayer`: `Block.vue` is the row WRAPPER, and two near-identical names
 * beside each other is the ambiguity this one is named to avoid.
 */
const store = useStore()
const controller = store.rows

const readOnly = useMarkput(s => s.props.readOnly)
const draggable = useMarkput(s => s.props.draggable)
const rows = useMarkput(s => s.tokens.nodes)
const hovered = useMarkput(() => controller.state.hovered)
const dragging = useMarkput(() => controller.state.dragging)
const drop = useMarkput(() => controller.state.drop)
const menu = useMarkput(() => controller.state.menu)
const geometry = useMarkput(() => controller.state.geometry)

const controlRef = store.tokens.control()
const setLayerRef = (el: unknown) => controlRef(unwrapEl(el))
const setMenuRef = (el: HTMLElement | null) => controller.menuElement(el)

const alwaysShowHandle = computed(() => getAlwaysShowHandle(draggable.value))

// The row the grip decorates: the dragged row while a drag is live, else the hovered one. The
// fallback is what `alwaysShowHandle` now means — one layer cannot paint a grip on every row,
// so the option is "one grip, on the row nearest the pointer", resting on the first row while
// the pointer is away. DECLARED BEHAVIOUR CHANGE on a published option.
const gripRow = computed<number | null>(
	() => dragging.value ?? hovered.value ?? (alwaysShowHandle.value ? (rows.value[0]?.id ?? null) : null)
)

// Geometry is MEASURED, not inherited from a `position: relative` ancestor: `geometry` is the
// container's resize/scroll clock and `flush: 'post'` puts the read after this patch painted.
//
// The GRIP alone: the drop indicator's line arrives already resolved on `state.drop`, measured by
// the `dragover` that resolved the placement it will perform, so the layer cannot paint an
// indicator anywhere but where the drop will land.
const gripBox = ref<RowBox | null>(null)
watchEffect(
	() => {
		void geometry.value
		gripBox.value = gripRow.value === null ? null : (controller.boxOf(gripRow.value) ?? null)
	},
	{flush: 'post'}
)

// A row that GROWS as the user types moves the grip with it, and the container's own observer
// says nothing when the container's size is fixed. Observing the ONE decorated row is the
// cheapest correct trigger.
let observer: ResizeObserver | undefined
watchEffect(
	() => {
		observer?.disconnect()
		observer = undefined
		const id = gripRow.value
		if (id === null) return
		const element = store.tokens.handle(id)?.element()
		if (!element) return
		observer = new ResizeObserver(() => {
			gripBox.value = controller.boxOf(id) ?? null
		})
		observer.observe(element)
	},
	{flush: 'post'}
)
onScopeDispose(() => observer?.disconnect())

// `left` is the ROW's left edge; `.SidePanel`'s negative margin hangs the band off it. The
// layer's own origin would put it on top of the text wherever core reserves no gutter
// (`draggable: false`).
const gripStyle = computed(() => ({
	top: `${gripBox.value?.top ?? 0}px`,
	left: `${gripBox.value?.left ?? 0}px`,
	height: `${gripBox.value?.height ?? 0}px`,
}))
// `left` says the DEPTH the drop will land at: core indents the line by the measured indent unit,
// so the indicator answers "where" and "how deep" at once.
const dropStyle = computed(() => {
	const line = drop.value?.line
	if (!line) return undefined
	return {top: `${line.top - 1}px`, left: `${line.left}px`, width: `${line.width}px`}
})
</script>

<template>
	<div :ref="setLayerRef" :class="styles.BlockControls">
		<!-- Painted but INVISIBLE while its row is being dragged, as the per-row panel was: the
		     grip stays mounted so its own `dragend` still fires (Chromium sends no mouseup for a
		     drag), and the pointer is away with the drag image anyway. -->
		<div
			v-if="!readOnly && gripRow !== null && gripBox"
			:class="[
				styles.SidePanel,
				alwaysShowHandle ? styles.SidePanelAlways : dragging === null && styles.SidePanelVisible,
			]"
			:style="gripStyle"
		>
			<!-- The grip is also the menu trigger, so it renders in block mode regardless;
			     `draggable` gates only the drag affordance it carries. -->
			<button
				type="button"
				:draggable="!!draggable"
				:class="[styles.GripButton, dragging !== null && styles.GripButtonDragging]"
				:aria-label="draggable ? 'Drag to reorder or click for options' : 'Block options'"
				@mousedown="controller.pinHover()"
				@dragstart="e => controller.beginDrag(gripRow!, e)"
				@dragend="controller.endDrag()"
				@click.prevent="
					e => controller.openMenu(gripRow!, (e.currentTarget as HTMLElement).getBoundingClientRect())
				"
			>
				<span :class="`${styles.Icon} ${styles.IconGrip}`" />
			</button>
		</div>

		<div v-if="dropStyle" :class="styles.DropIndicator" :style="dropStyle" />

		<Popup
			v-if="menu"
			:attach-ref="setMenuRef"
			:style="{top: menu.top + 'px', left: menu.left + 'px', pointerEvents: 'auto'}"
		>
			<List>
				<ListItem v-for="item in ROW_MENU_ITEMS" :key="item.label" @mousedown.prevent="item.run(controller)">
					<span :class="item.iconClass" />
					<span>{{ item.label }}</span>
				</ListItem>
			</List>
		</Popup>
	</div>
</template>

// packages/react/markput/src/components/BlockControls.tsx
import {ROW_MENU_ITEMS, cx, getAlwaysShowHandle} from '@markput/core'
import type {RowBox} from '@markput/core'
import {memo, useEffect, useLayoutEffect, useMemo, useState} from 'react'

import {useMarkput} from '../lib/hooks/useMarkput'
import {List} from './Popup/List'
import {ListItem} from './Popup/ListItem'
import {Popup} from './Popup/Popup'

import styles from '@markput/core/styles.module.css'

/**
 * ONE absolutely positioned row-controls layer per editor: it paints the grip, the drop indicator
 * and the row menu at row boxes it MEASURES, where `.Block { position: relative }` used to make
 * them free inside every row.
 *
 * `BlockControls`, not `BlockLayer`: `Block.tsx` is the row WRAPPER, and two near-identical names
 * beside each other is the ambiguity this one is named to avoid.
 *
 * It lives INSIDE the container — the alternative, a new wrapper element in `MarkedInput`, would
 * impose a published DOM change on every consumer for internal convenience. That puts it inside
 * the editing host, so it registers as a `control()` root: one registration for the whole editor,
 * where the per-row controls filed up to four PER ROW, and everything painted inside it inherits
 * `isContentEditable === false` from it.
 */
const iconGrip = `${styles.Icon} ${styles.IconGrip}`

export const BlockControls = memo(() => {
	const {controller, tokens, readOnly, draggable, rows, hovered, dragging, drop, menu, geometry} = useMarkput(s => ({
		controller: s.rows,
		tokens: s.tokens,
		readOnly: s.props.readOnly,
		draggable: s.props.draggable,
		rows: s.tokens.nodes,
		hovered: s.rows.state.hovered,
		dragging: s.rows.state.dragging,
		drop: s.rows.state.drop,
		menu: s.rows.state.menu,
		geometry: s.rows.state.geometry,
	}))
	const controlRef = useMemo(() => tokens.control(), [tokens])
	const alwaysShowHandle = useMemo(() => getAlwaysShowHandle(draggable), [draggable])

	// The row the grip decorates: the dragged row while a drag is live, else the hovered one.
	// The fallback is what `alwaysShowHandle` now means — one layer cannot paint a grip on every
	// row, so the option is "one grip, on the row nearest the pointer", resting on the first row
	// while the pointer is away. DECLARED BEHAVIOUR CHANGE on a published option.
	const gripRow = dragging ?? hovered ?? (alwaysShowHandle ? (rows[0]?.id ?? null) : null)

	// Geometry is MEASURED, not inherited from a `position: relative` ancestor. In a layout
	// effect, so it sees the painted DOM of this very commit, and re-run on `geometry` — the
	// container's own resize/scroll clock.
	//
	// The GRIP alone: the drop indicator's line arrives already resolved on `state.drop`, measured
	// by the `dragover` that resolved the placement it will perform, so the layer cannot paint an
	// indicator anywhere but where the drop will land.
	const [gripBox, setGripBox] = useState<RowBox | null>(null)
	useLayoutEffect(() => {
		setGripBox(gripRow === null ? null : (controller.boxOf(gripRow) ?? null))
	}, [controller, gripRow, geometry])

	// A row that GROWS as the user types moves the grip with it, and the container's own observer
	// says nothing when the container's size is fixed. Observing the ONE decorated row is the
	// cheapest correct trigger.
	useEffect(() => {
		if (gripRow === null) return
		const element = tokens.handle(gripRow)?.element()
		if (!element) return
		const observer = new ResizeObserver(() => setGripBox(controller.boxOf(gripRow) ?? null))
		observer.observe(element)
		return () => observer.disconnect()
	}, [controller, tokens, gripRow])

	return (
		<div ref={controlRef} className={styles.BlockControls}>
			{!readOnly && gripRow !== null && gripBox !== null && (
				<div
					className={cx(
						styles.SidePanel,
						// Painted but INVISIBLE while its row is being dragged, as the per-row
						// panel was: the grip stays mounted so its own `dragend` still fires
						// (Chromium sends no mouseup for a drag), and the pointer is away with
						// the drag image anyway.
						alwaysShowHandle ? styles.SidePanelAlways : dragging === null && styles.SidePanelVisible
					)}
					// `left` is the ROW's left edge; `.SidePanel`'s negative margin hangs the
					// band off it. The layer's own origin would put it on top of the text
					// wherever core reserves no gutter — `draggable: false`.
					style={{top: gripBox.top, left: gripBox.left, height: gripBox.height}}
				>
					<button
						type="button"
						// The grip is also the menu trigger, so it renders in block mode regardless;
						// `draggable` gates only the drag affordance it carries.
						draggable={!!draggable}
						className={cx(styles.GripButton, dragging !== null && styles.GripButtonDragging)}
						aria-label={draggable ? 'Drag to reorder or click for options' : 'Block options'}
						onMouseDown={controller.pinHover}
						onDragStart={e => controller.beginDrag(gripRow, e.nativeEvent)}
						onDragEnd={() => controller.endDrag()}
						onClick={e => {
							e.preventDefault()
							controller.openMenu(gripRow, e.currentTarget.getBoundingClientRect())
						}}
					>
						<span className={iconGrip} />
					</button>
				</div>
			)}

			{drop && (
				<div
					className={styles.DropIndicator}
					// `left` says the DEPTH the drop will land at: core indents the line by the
					// measured indent unit, so the indicator answers "where" and "how deep" at once.
					style={{top: drop.line.top - 1, left: drop.line.left, width: drop.line.width}}
				/>
			)}

			{menu && (
				<Popup
					ref={(el: HTMLElement | null) => {
						controller.menuElement(el)
					}}
					style={{top: menu.top, left: menu.left, pointerEvents: 'auto'}}
				>
					<List>
						{ROW_MENU_ITEMS.map(item => (
							<ListItem key={item.label} onClick={() => item.run(controller)}>
								<span className={item.iconClass} />
								<span>{item.label}</span>
							</ListItem>
						))}
					</List>
				</Popup>
			)}
		</div>
	)
})

BlockControls.displayName = 'BlockControls'
