// packages/vue/markput/src/components/Block.vue
<script setup lang="ts">
import type {Token as TokenType} from '@markput/core'

import {useStore} from '../lib/hooks/useStore'
import BlockMenu from './BlockMenu.vue'
import DragHandle from './DragHandle.vue'
import DropIndicator from './DropIndicator.vue'
import Token from './Token.vue'

import styles from '@markput/core/styles.module.css'

const props = defineProps<{token: TokenType; blockIndex: number}>()

const store = useStore()
const blockStore = store.blocks.get(props.token)
const isDragging = blockStore.state.isDragging.use()
</script>

<template>
	<div
		:ref="el => blockStore.attachContainer(el as HTMLElement | null, props.blockIndex, store.events)"
		v-bind="{'data-testid': 'block'}"
		:class="styles.Block"
		:style="{opacity: isDragging ? 0.4 : 1}"
	>
		<DropIndicator :token="token" position="before" />
		<DragHandle :token="token" :block-index="blockIndex" />
		<Token :mark="token" />
		<DropIndicator :token="token" position="after" />
		<BlockMenu :token="token" />
	</div>
</template>

// packages/react/markput/src/components/Block.tsx
import type {Token as TokenType} from '@markput/core'
import {memo} from 'react'

import {useStore} from '../lib/providers/StoreContext'
import {BlockMenu} from './BlockMenu'
import {DragHandle} from './DragHandle'
import {DropIndicator} from './DropIndicator'
import {Token} from './Token'

import styles from '@markput/core/styles.module.css'

interface BlockProps {
	token: TokenType
	blockIndex: number
}

export const Block = memo(({token, blockIndex}: BlockProps) => {
	const store = useStore()
	const [ContainerComponent, containerProps] = store.slot.block.use()

	const blockStore = store.blocks.get(token)
	const isDragging = blockStore.state.isDragging.use()

	return (
		<ContainerComponent
			ref={(el: HTMLElement | null) => blockStore.attachContainer(el, blockIndex, store.event)}
			data-testid="block"
			{...containerProps}
			className={styles.Block}
			style={{opacity: isDragging ? 0.4 : 1}}
		>
			<DropIndicator token={token} position="before" />

			<DragHandle token={token} blockIndex={blockIndex} />

			<Token mark={token} />

			<DropIndicator token={token} position="after" />

			<BlockMenu token={token} />
		</ContainerComponent>
	)
})

Block.displayName = 'Block'
