// packages/vue/markput/src/components/BlockContainer.vue
<script setup lang="ts">
import type {Token as CoreToken} from '@markput/core'
import {splitTokensIntoBlocks, reorderBlocks, parseWithParser} from '@markput/core'
import {computed} from 'vue'

import {useStore} from '../lib/hooks/useStore'
import {resolveSlot, resolveSlotProps} from '../lib/slots'
import DraggableBlock from './DraggableBlock.vue'
import Token from './Token.vue'

const store = useStore()
const tokens = store.state.tokens.use()
const slots = store.state.slots.use()
const slotProps = store.state.slotProps.use()
const className = store.state.className.use()
const style = store.state.style.use()
const readOnly = store.state.readOnly.use()
const value = store.state.value.use()
const onChange = store.state.onChange.use()
const key = store.key

const containerTag = computed(() => resolveSlot('container', slots.value))
const containerProps = computed(() => resolveSlotProps('container', slotProps.value))

const blocks = computed(() => splitTokensIntoBlocks(tokens.value))

function handleReorder(sourceIndex: number, targetIndex: number) {
	if (!value.value || !onChange.value) return
	const newValue = reorderBlocks(value.value, blocks.value, sourceIndex, targetIndex)
	if (newValue !== value.value) {
		const newTokens = parseWithParser(store, newValue)
		store.state.tokens.set(newTokens)
		store.state.previousValue.set(newValue)
		onChange.value(newValue)
	}
}
</script>

<template>
	<component
		:is="containerTag"
		:ref="(el: HTMLDivElement | null) => (store.refs.container = el)"
		v-bind="containerProps"
		:class="className"
		:style="style"
	>
		<DraggableBlock
			v-for="(block, index) in blocks"
			:key="block.id"
			:block-index="index"
			:read-only="readOnly"
			@reorder="handleReorder"
		>
			<Token v-for="token in block.tokens" :key="key.get(token)" :mark="token" />
		</DraggableBlock>
	</component>
</template>

// packages/react/markput/src/components/BlockContainer.tsx
import {splitTokensIntoBlocks, reorderBlocks, parseWithParser, type Block} from '@markput/core'
import {memo, useCallback, useMemo, useRef} from 'react'

import {useStore} from '../lib/hooks/useStore'
import {resolveSlot, resolveSlotProps} from '../lib/utils/resolveSlot'
import {DraggableBlock} from './DraggableBlock'
import {Token} from './Token'

export const BlockContainer = memo(() => {
	const store = useStore()
	const tokens = store.state.tokens.use()
	const slots = store.state.slots.use()
	const slotProps = store.state.slotProps.use()
	const className = store.state.className.use()
	const style = store.state.style.use()
	const readOnly = store.state.readOnly.use()
	const value = store.state.value.use()
	const onChange = store.state.onChange.use()
	const key = store.key
	const refs = store.refs

	const ContainerComponent = useMemo(() => resolveSlot('container', slots), [slots])
	const containerProps = useMemo(() => resolveSlotProps('container', slotProps), [slotProps])

	const blocks = useMemo(() => splitTokensIntoBlocks(tokens), [tokens])
	const blocksRef = useRef<Block[]>(blocks)
	blocksRef.current = blocks

	const handleReorder = useCallback(
		(sourceIndex: number, targetIndex: number) => {
			if (!value || !onChange) return
			const currentBlocks = blocksRef.current
			const newValue = reorderBlocks(value, currentBlocks, sourceIndex, targetIndex)
			if (newValue !== value) {
				const newTokens = parseWithParser(store, newValue)
				store.state.tokens.set(newTokens)
				store.state.previousValue.set(newValue)
				onChange(newValue)
			}
		},
		[store, value, onChange]
	)

	return (
		<ContainerComponent
			ref={(el: HTMLDivElement | null) => (refs.container = el)}
			{...containerProps}
			className={className}
			style={style}
		>
			{blocks.map((block, index) => (
				<DraggableBlock key={block.id} blockIndex={index} readOnly={readOnly} onReorder={handleReorder}>
					{block.tokens.map(token => (
						<Token key={key.get(token)} mark={token} />
					))}
				</DraggableBlock>
			))}
		</ContainerComponent>
	)
})

BlockContainer.displayName = 'BlockContainer'
