// packages/vue/markput/src/components/TokenChildren.vue
<script lang="ts">
import {defineComponent, h, onBeforeUnmount} from 'vue'

import {useStore} from '../lib/hooks/useStore'

export default defineComponent({
	name: 'TokenChildren',
	props: {
		/** The owning mark's stable id — the key `tokens.children` registers under since S1.8. */
		ownerId: {type: Number, required: true},
	},
	setup(props, {slots}) {
		const store = useStore()
		const childSequenceRef = store.tokens.children(props.ownerId)

		const setElement = (el: unknown) => {
			childSequenceRef(el instanceof HTMLElement ? el : null)
		}

		onBeforeUnmount(() => {
			childSequenceRef(null)
		})

		return () => h('span', {ref: setElement, style: {display: 'contents'}}, slots.default?.())
	},
})
</script>

// packages/react/markput/src/components/TokenChildren.tsx
import type {CSSProperties, ReactNode} from 'react'
import {memo, useMemo} from 'react'

import {useMarkput} from '../lib/hooks/useMarkput'

const sequenceHostStyle: CSSProperties = {display: 'contents'}

/** `ownerId` is the owning mark's stable id — the key `tokens.children` registers under since S1.8. */
export const TokenChildren = memo(({ownerId, children}: {ownerId: number; children: ReactNode}) => {
	const {tokens} = useMarkput(s => ({tokens: s.tokens}))
	const ref = useMemo(() => tokens.children(ownerId), [tokens, ownerId])

	return (
		<span ref={ref} style={sequenceHostStyle}>
			{children}
		</span>
	)
})

TokenChildren.displayName = 'TokenChildren'
