// packages/react/markput/src/components/Suggestions/Suggestions.tsx
import {filterSuggestions, navigateSuggestions} from '@markput/core'
import {useEffect, useMemo, useRef, useState} from 'react'

import {useMarkput} from '../../lib/hooks/useMarkput'
import {useOverlay} from '../../lib/hooks/useOverlay'
import {List} from '../Popup/List'
import {ListItem} from '../Popup/ListItem'
import {Popup} from '../Popup/Popup'

export const Suggestions = () => {
	const container = useMarkput(s => s.slots.container)
	const {match, select, style, ref} = useOverlay()
	const [active, setActive] = useState(NaN)
	const data = match?.option.overlay?.data ?? []
	const filtered = useMemo(() => (match ? filterSuggestions(data, match.value) : []), [match, data])
	const length = filtered.length

	const activeRef = useRef(active)
	activeRef.current = active
	const filteredRef = useRef(filtered)
	filteredRef.current = filtered

	useEffect(() => {
		if (!container) return

		const handler = (event: KeyboardEvent) => {
			const result = navigateSuggestions(event.key, activeRef.current, length)
			switch (result.action) {
				case 'up':
				case 'down':
					event.preventDefault()
					setActive(result.index)
					break
				case 'select': {
					event.preventDefault()
					const suggestion = filteredRef.current[result.index]
					select({value: suggestion, meta: result.index.toString()})
					break
				}
				case 'none':
					break
			}
		}

		container.addEventListener('keydown', handler)
		return () => container.removeEventListener('keydown', handler)
	}, [container, length, select])

	if (!filtered.length) return null

	return (
		<Popup ref={ref} style={style}>
			<List>
				{filtered.map((suggestion, index) => (
					<ListItem
						key={suggestion}
						active={index === active}
						onClick={() => select({value: suggestion, meta: index.toString()})}
					>
						{suggestion}
					</ListItem>
				))}
			</List>
		</Popup>
	)
}

// packages/vue/markput/src/components/Suggestions/Suggestions.vue
<script setup lang="ts">
import {filterSuggestions, navigateSuggestions} from '@markput/core'
import {ref, computed, onMounted, onUnmounted} from 'vue'

import {useOverlay} from '../../lib/hooks/useOverlay'
import {useStore} from '../../lib/hooks/useStore'
import List from '../Popup/List.vue'
import ListItem from '../Popup/ListItem.vue'
import Popup from '../Popup/Popup.vue'

const store = useStore()
const {match, select, style: overlayStyle, ref: overlayRef} = useOverlay()
const active = ref(NaN)

const data = computed(() => match.value?.option.overlay?.data || [])
const filtered = computed(() => {
	const search = match.value?.value ?? ''
	return filterSuggestions(data.value as string[], search)
})

function handleKeyDown(event: KeyboardEvent) {
	const result = navigateSuggestions(event.key, active.value, filtered.value.length)
	switch (result.action) {
		case 'up':
		case 'down':
			event.preventDefault()
			active.value = result.index
			break
		case 'select':
			event.preventDefault()
			const suggestion = filtered.value[result.index]
			if (suggestion) {
				select({value: suggestion, meta: result.index.toString()})
			}
			break
	}
}

onMounted(() => {
	const container = store.feature.slots.container()
	if (container) container.addEventListener('keydown', handleKeyDown)
})

onUnmounted(() => {
	const container = store.feature.slots.container()
	if (container) container.removeEventListener('keydown', handleKeyDown)
})

function handleItemClick(suggestion: string, index: number) {
	select({value: suggestion, meta: index.toString()})
}

function setOverlayRef(el: HTMLElement | null) {
	overlayRef.current = el
}
</script>

<template>
	<Popup v-if="filtered.length" :style="overlayStyle" :attach-ref="setOverlayRef">
		<List>
			<ListItem
				v-for="(suggestion, index) in filtered"
				:key="suggestion"
				:active="index === active"
				@click="handleItemClick(suggestion, index)"
			>
				{{ suggestion }}
			</ListItem>
		</List>
	</Popup>
</template>
